from tinygrad.uop import auto, FastEnum

# ***** RDNA3 Ops *****
# small endian
class RDNA3Ops(FastEnum):
    # ** SOP2 - 2in - 1out - 32bit literals **
    S_ADD_U32 = auto(); S_SUB_U32 = auto(); S_ADD_I32 = auto()
    S_SUB_I32 = auto(); S_ADDC_U32 = auto(); S_SUBB_U32 = auto()
    S_ABSDIFF_I32 = auto(); S_LSHL_B32 = auto(); S_LSHL_B64 = auto()
    S_LSHR_B32 = auto(); S_LSHR_B64 = auto(); S_ASHR_I32 = auto()
    S_ASHR_I64 = auto(); S_LSHL1_ADD_U32 = auto(); S_LSHL2_ADD_U32 = auto()
    S_LSHL3_ADD_U32 = auto(); S_LSHL4_ADD_U32 = auto(); S_MIN_I32 = auto()
    S_MIN_U32 = auto(); S_MAX_I32 = auto(); S_MAX_U32 = auto()
    S_AND_B32 = auto(); S_AND_B64 = auto(); S_OR_B32 = auto()
    S_OR_B64 = auto(); S_XOR_B32 = auto(); S_XOR_B64 = auto()
    S_NAND_B32 = auto(); S_NAND_B64 = auto(); S_NOR_B32 = auto()
    S_NOR_B64 = auto(); S_XNOR_B32 = auto(); S_XNOR_B64 = auto()
    S_AND_NOT1_B32 = auto(); S_AND_NOT1_B64 = auto(); S_OR_NOT1_B32 = auto()
    S_OR_NOT1_B64 = auto(); S_BFE_U32 = auto(); S_BFE_I32 = auto()
    S_BFE_U64 = auto(); S_BFE_I64 = auto(); S_BFM_B32 = auto()
    S_BFM_B64 = auto(); S_MUL_I32 = auto(); S_MUL_HI_U32 = auto()
    S_MUL_HI_I32 = auto(); S_CSELECT_B32 = auto(); S_CSELECT_B64 = auto()
    S_PACK_LL_B32_B16 = auto(); S_PACK_LH_B32_B16 = auto(); S_PACK_HH_B32_B16 = auto()
    S_PACK_HL_B32_B16 = auto(); S_ADD_F32 = auto(); S_SUB_F32 = auto()
    S_MIN_F32 = auto(); S_MAX_F32 = auto(); S_MUL_F32 = auto()
    S_FMAAK_F32 = auto(); S_FMAMK_F32 = auto(); S_FMAC_F32 = auto()
    S_CVT_PK_RTZ_F16_F32 = auto(); S_ADD_F16 = auto(); S_SUB_F16 = auto()
    S_MIN_F16 = auto(); S_MAX_F16 = auto(); S_MUL_F16 = auto()
    S_FMAC_F16 = auto()

    # ** SOPK - 1in - 1out - SIMM16 **
    S_MOVK_I32 = auto(); S_VERSION = auto(); S_CMOVK_I32 = auto()
    S_CMPK_EQ_I32 = auto(); S_CMPK_LG_I32 = auto(); S_CMPK_GT_I32 = auto()
    S_CMPK_GE_I32 = auto(); S_CMPK_LT_I32 = auto(); S_CMPK_LE_I32 = auto()
    S_CMPK_EQ_U32 = auto(); S_CMPK_LG_U32 = auto(); S_CMPK_GT_U32 = auto()
    S_CMPK_GE_U32 = auto(); S_CMPK_LT_U32 = auto(); S_CMPK_LE_U32 = auto()
    S_ADDK_I32 = auto(); S_MULK_I32 = auto(); S_GETREG_B32 = auto()
    S_SETREG_B32 = auto(); S_SETREG_IMM32_B32 = auto(); S_CALL_B64 = auto()
    S_SUBVECTOR_LOOP_BEGIN = auto(); S_SUBVECTOR_LOOP_END = auto(); S_WAITCNT_VSCNT = auto()
    S_WAITCNT_VMCNT = auto(); S_WAITCNT_EXPCNT = auto(); S_WAITCNT_LGKMCNT = auto()

    # ** SOP1 - 1in - 1out - 32bit literals **
    S_MOV_B32 = auto(); S_MOV_B64 = auto(); S_CMOV_B32 = auto()
    S_CMOV_B64 = auto(); S_BREV_B32 = auto(); S_BREV_B64 = auto()
    S_CTZ_I32_B32 = auto(); S_CTZ_I32_B64 = auto(); S_CLZ_I32_U32 = auto()
    S_CLZ_I32_U64 = auto(); S_CLS_I32 = auto(); S_CLS_I32_I64 = auto()
    S_SEXT_I32_I8 = auto(); S_SEXT_I32_I16 = auto(); S_BITSET0_B32 = auto()
    S_BITSET0_B64 = auto(); S_BITSET1_B32 = auto(); S_BITSET1_B64 = auto()
    S_BITREPLICATE_B64_B32 = auto(); S_ABS_I32 = auto(); S_BCNT0_I32_B32 = auto()
    S_BCNT0_I32_B64 = auto(); S_BCNT1_I32_B32 = auto(); S_BCNT1_I32_B64 = auto()
    S_QUADMASK_B32 = auto(); S_QUADMASK_B64 = auto(); S_WQM_B32 = auto()
    S_WQM_B64 = auto(); S_NOT_B32 = auto(); S_NOT_B64 = auto()
    S_AND_SAVEEXEC_B32 = auto(); S_AND_SAVEEXEC_B64 = auto(); S_OR_SAVEEXEC_B32 = auto()
    S_OR_SAVEEXEC_B64 = auto(); S_XOR_SAVEEXEC_B32 = auto(); S_XOR_SAVEEXEC_B64 = auto()
    S_NAND_SAVEEXEC_B32 = auto(); S_NAND_SAVEEXEC_B64 = auto(); S_NOR_SAVEEXEC_B32 = auto()
    S_NOR_SAVEEXEC_B64 = auto(); S_XNOR_SAVEEXEC_B32 = auto(); S_XNOR_SAVEEXEC_B64 = auto()
    S_AND_NOT0_SAVEEXEC_B32 = auto(); S_AND_NOT0_SAVEEXEC_B64 = auto(); S_OR_NOT0_SAVEEXEC_B32 = auto()
    S_OR_NOT0_SAVEEXEC_B64 = auto(); S_AND_NOT1_SAVEEXEC_B32 = auto(); S_AND_NOT1_SAVEEXEC_B64 = auto()
    S_OR_NOT1_SAVEEXEC_B32 = auto(); S_OR_NOT1_SAVEEXEC_B64 = auto(); S_AND_NOT0_WREXEC_B32 = auto()
    S_AND_NOT0_WREXEC_B64 = auto(); S_AND_NOT1_WREXEC_B32 = auto(); S_AND_NOT1_WREXEC_B64 = auto()
    S_MOVRELS_B32 = auto(); S_MOVRELS_B64 = auto(); S_MOVRELD_B32 = auto()
    S_MOVRELD_B64 = auto(); S_MOVRELSD_2_B32 = auto(); S_GETPC_B64 = auto()
    S_SETPC_B64 = auto(); S_SWAPPC_B64 = auto(); S_RFE_B64 = auto()
    S_SENDMSG_RTN_B32 = auto(); S_SENDMSG_RTN_B64 = auto(); S_CEIL_F32 = auto()
    S_FLOOR_F32 = auto(); S_TRUNC_F32 = auto(); S_RNDNE_F32 = auto()
    S_CVT_F32_I32 = auto(); S_CVT_F32_U32 = auto(); S_CVT_I32_F32 = auto()
    S_CVT_U32_F32 = auto(); S_CVT_F16_F32 = auto(); S_CVT_F32_F16 = auto()
    S_CVT_HI_F32_F16 = auto(); S_CEIL_F16 = auto(); S_FLOOR_F16 = auto()
    S_TRUNC_F16 = auto(); S_RNDNE_F16 = auto()

    # ** SOPC - 2in - 1out SCC - 32bit literals **
    S_CMP_EQ_I32 = auto(); S_CMP_LG_I32 = auto(); S_CMP_GT_I32 = auto()
    S_CMP_GE_I32 = auto(); S_CMP_LT_I32 = auto(); S_CMP_LE_I32 = auto()
    S_CMP_EQ_U32 = auto(); S_CMP_LG_U32 = auto(); S_CMP_GT_U32 = auto()
    S_CMP_GE_U32 = auto(); S_CMP_LT_U32 = auto(); S_CMP_LE_U32 = auto()
    S_BITCMP0_B32 = auto(); S_BITCMP1_B32 = auto(); S_BITCMP0_B64 = auto()
    S_BITCMP1_B64 = auto(); S_CMP_EQ_U64 = auto(); S_CMP_LG_U64 = auto()
    S_CMP_LT_F32 = auto(); S_CMP_EQ_F32 = auto(); S_CMP_LE_F32 = auto()
    S_CMP_GT_F32 = auto(); S_CMP_LG_F32 = auto(); S_CMP_GE_F32 = auto()
    S_CMP_O_F32 = auto(); S_CMP_U_F32 = auto(); S_CMP_NGE_F32 = auto()
    S_CMP_NLG_F32 = auto(); S_CMP_NGT_F32 = auto(); S_CMP_NLE_F32 = auto()
    S_CMP_NEQ_F32 = auto(); S_CMP_NLT_F32 = auto(); S_CMP_LT_F16 = auto()
    S_CMP_EQ_F16 = auto(); S_CMP_LE_F16 = auto(); S_CMP_GT_F16 = auto()
    S_CMP_LG_F16 = auto(); S_CMP_GE_F16 = auto(); S_CMP_O_F16 = auto()
    S_CMP_U_F16 = auto(); S_CMP_NGE_F16 = auto(); S_CMP_NLG_F16 = auto()
    S_CMP_NGT_F16 = auto(); S_CMP_NLE_F16 = auto(); S_CMP_NEQ_F16 = auto()
    S_CMP_NLT_F16 = auto()

    # ** SOPP - 1in - control flow - SIMM16 **
    S_NOP = auto(); S_SETKILL = auto(); S_SETHALT = auto()
    S_SLEEP = auto(); S_SET_INST_PREFETCH_DISTANCE = auto(); S_CLAUSE = auto()
    S_DELAY_ALU = auto(); S_WAITCNT_DEPCTR = auto(); S_WAITCNT = auto()
    S_WAIT_IDLE = auto(); S_WAIT_EVENT = auto(); S_TRAP = auto()
    S_ROUND_MODE = auto(); S_DENORM_MODE = auto(); S_CODE_END = auto()
    S_BRANCH = auto(); S_CBRANCH_SCC0 = auto(); S_CBRANCH_SCC1 = auto()
    S_CBRANCH_VCCZ = auto(); S_CBRANCH_VCCNZ = auto(); S_CBRANCH_EXECZ = auto()
    S_CBRANCH_EXECNZ = auto(); S_CBRANCH_CDBGSYS = auto(); S_CBRANCH_CDBGUSER = auto()
    S_CBRANCH_CDBGSYS_OR_USER = auto(); S_CBRANCH_CDBGSYS_AND_USER = auto(); S_ENDPGM = auto()
    S_ENDPGM_SAVED = auto(); S_ENDPGM_ORDERED_PS_DONE = auto(); S_WAKEUP = auto()
    S_SETPRIO = auto(); S_SENDMSG = auto(); S_SENDMSGHALT = auto()
    S_INCPERFLEVEL = auto(); S_DECPERFLEVEL = auto(); S_TTRACEDATA = auto()
    S_TTRACEDATA_IMM = auto(); S_ICACHE_INV = auto(); S_BARRIER = auto()

    # ** SMEM - memory in - SGPR out **
    S_LOAD_B32 = auto(); S_LOAD_B64 = auto(); S_LOAD_B128 = auto()
    S_LOAD_B256 = auto(); S_LOAD_B512 = auto(); S_BUFFER_LOAD_B32 = auto()
    S_BUFFER_LOAD_B64 = auto(); S_BUFFER_LOAD_B128 = auto(); S_BUFFER_LOAD_B256 = auto()
    S_BUFFER_LOAD_B512 = auto(); S_GL1_INV = auto(); S_DCACHE_INV = auto()
    S_ATC_PROBE = auto(); S_ATC_PROBE_BUFFER = auto()

    # ** VOP2 - 2in - 1out - 32bit literals, DPP **
    V_CNDMASK_B32 = auto(); V_DOT2ACC_F32_F16 = auto(); V_ADD_F32 = auto()
    V_SUB_F32 = auto(); V_SUBREV_F32 = auto(); V_FMAC_DX9_ZERO_F32 = auto()
    V_MUL_DX9_ZERO_F32 = auto(); V_MUL_F32 = auto(); V_MUL_I32_I24 = auto()
    V_MUL_HI_I32_I24 = auto(); V_MUL_U32_U24 = auto(); V_MUL_HI_U32_U24 = auto()
    V_MIN_F32 = auto(); V_MAX_F32 = auto(); V_MIN_I32 = auto()
    V_MAX_I32 = auto(); V_MIN_U32 = auto(); V_MAX_U32 = auto()
    V_LSHLREV_B32 = auto(); V_LSHRREV_B32 = auto(); V_ASHRREV_I32 = auto()
    V_AND_B32 = auto(); V_OR_B32 = auto(); V_XOR_B32 = auto()
    V_XNOR_B32 = auto(); V_ADD_CO_CI_U32 = auto(); V_SUB_CO_CI_U32 = auto()
    V_SUBREV_CO_CI_U32 = auto(); V_ADD_NC_U32 = auto(); V_SUB_NC_U32 = auto()
    V_SUBREV_NC_U32 = auto(); V_FMAC_F32 = auto(); V_FMAMK_F32 = auto()
    V_FMAAK_F32 = auto(); V_CVT_PK_RTZ_F16_F32 = auto(); V_ADD_F16 = auto()
    V_SUB_F16 = auto(); V_SUBREV_F16 = auto(); V_MUL_F16 = auto()
    V_FMAC_F16 = auto(); V_FMAMK_F16 = auto(); V_FMAAK_F16 = auto()
    V_MAX_F16 = auto(); V_MIN_F16 = auto(); V_LDEXP_F16 = auto()
    V_PK_FMAC_F16 = auto()

    # ** VOP1 - 1in - 1out - 32bit literals, DPP **
    V_NOP = auto(); V_MOV_B32 = auto(); V_READFIRSTLANE_B32 = auto()
    V_CVT_I32_F64 = auto(); V_CVT_F64_I32 = auto(); V_CVT_F32_I32 = auto()
    V_CVT_F32_U32 = auto(); V_CVT_U32_F32 = auto(); V_CVT_I32_F32 = auto()
    V_CVT_F16_F32 = auto(); V_CVT_F32_F16 = auto(); V_CVT_NEAREST_I32_F32 = auto()
    V_CVT_FLOOR_I32_F32 = auto(); V_CVT_OFF_F32_I4 = auto(); V_CVT_F32_F64 = auto()
    V_CVT_F64_F32 = auto(); V_CVT_F32_UBYTE0 = auto(); V_CVT_F32_UBYTE1 = auto()
    V_CVT_F32_UBYTE2 = auto(); V_CVT_F32_UBYTE3 = auto(); V_CVT_U32_F64 = auto()
    V_CVT_F64_U32 = auto(); V_TRUNC_F64 = auto(); V_CEIL_F64 = auto()
    V_RNDNE_F64 = auto(); V_FLOOR_F64 = auto(); V_PIPEFLUSH = auto()
    V_MOV_B16 = auto(); V_FRACT_F32 = auto(); V_TRUNC_F32 = auto()
    V_CEIL_F32 = auto(); V_RNDNE_F32 = auto(); V_FLOOR_F32 = auto()
    V_EXP_F32 = auto(); V_LOG_F32 = auto(); V_RCP_F32 = auto()
    V_RCP_IFLAG_F32 = auto(); V_RSQ_F32 = auto(); V_RCP_F64 = auto()
    V_RSQ_F64 = auto(); V_SQRT_F32 = auto(); V_SQRT_F64 = auto()
    V_SIN_F32 = auto(); V_COS_F32 = auto(); V_NOT_B32 = auto()
    V_BFREV_B32 = auto(); V_CLZ_I32_U32 = auto(); V_CTZ_I32_B32 = auto()
    V_CLS_I32 = auto(); V_FREXP_EXP_I32_F64 = auto(); V_FREXP_MANT_F64 = auto()
    V_FRACT_F64 = auto(); V_FREXP_EXP_I32_F32 = auto(); V_FREXP_MANT_F32 = auto()
    V_MOVRELD_B32 = auto(); V_MOVRELS_B32 = auto(); V_MOVRELSD_B32 = auto()
    V_MOVRELSD_2_B32 = auto(); V_CVT_F16_U16 = auto(); V_CVT_F16_I16 = auto()
    V_CVT_U16_F16 = auto(); V_CVT_I16_F16 = auto(); V_RCP_F16 = auto()
    V_SQRT_F16 = auto(); V_RSQ_F16 = auto(); V_LOG_F16 = auto()
    V_EXP_F16 = auto(); V_FREXP_MANT_F16 = auto(); V_FREXP_EXP_I16_F16 = auto()
    V_FLOOR_F16 = auto(); V_CEIL_F16 = auto(); V_TRUNC_F16 = auto()
    V_RNDNE_F16 = auto(); V_FRACT_F16 = auto(); V_SIN_F16 = auto()
    V_COS_F16 = auto(); V_SAT_PK_U8_I16 = auto(); V_CVT_NORM_I16_F16 = auto()
    V_CVT_NORM_U16_F16 = auto(); V_SWAP_B32 = auto(); V_SWAP_B16 = auto()
    V_PERMLANE64_B32 = auto(); V_SWAPREL_B32 = auto(); V_NOT_B16 = auto()
    V_CVT_I32_I16 = auto(); V_CVT_U32_U16 = auto()

    # ** VOPC - 2in - 1out VCC - 32bit literals **
    V_CMP_F_F16 = auto(); V_CMP_LT_F16 = auto(); V_CMP_EQ_F16 = auto()
    V_CMP_LE_F16 = auto(); V_CMP_GT_F16 = auto(); V_CMP_LG_F16 = auto()
    V_CMP_GE_F16 = auto(); V_CMP_O_F16 = auto(); V_CMP_U_F16 = auto()
    V_CMP_NGE_F16 = auto(); V_CMP_NLG_F16 = auto(); V_CMP_NGT_F16 = auto()
    V_CMP_NLE_F16 = auto(); V_CMP_NEQ_F16 = auto(); V_CMP_NLT_F16 = auto()
    V_CMP_T_F16 = auto(); V_CMP_F_F32 = auto(); V_CMP_LT_F32 = auto()
    V_CMP_EQ_F32 = auto(); V_CMP_LE_F32 = auto(); V_CMP_GT_F32 = auto()
    V_CMP_LG_F32 = auto(); V_CMP_GE_F32 = auto(); V_CMP_O_F32 = auto()
    V_CMP_U_F32 = auto(); V_CMP_NGE_F32 = auto(); V_CMP_NLG_F32 = auto()
    V_CMP_NGT_F32 = auto(); V_CMP_NLE_F32 = auto(); V_CMP_NEQ_F32 = auto()
    V_CMP_NLT_F32 = auto(); V_CMP_T_F32 = auto(); V_CMP_F_F64 = auto()
    V_CMP_LT_F64 = auto(); V_CMP_EQ_F64 = auto(); V_CMP_LE_F64 = auto()
    V_CMP_GT_F64 = auto(); V_CMP_LG_F64 = auto(); V_CMP_GE_F64 = auto()
    V_CMP_O_F64 = auto(); V_CMP_U_F64 = auto(); V_CMP_NGE_F64 = auto()
    V_CMP_NLG_F64 = auto(); V_CMP_NGT_F64 = auto(); V_CMP_NLE_F64 = auto()
    V_CMP_NEQ_F64 = auto(); V_CMP_NLT_F64 = auto(); V_CMP_T_F64 = auto()
    V_CMP_LT_I16 = auto(); V_CMP_EQ_I16 = auto(); V_CMP_LE_I16 = auto()
    V_CMP_GT_I16 = auto(); V_CMP_NE_I16 = auto(); V_CMP_GE_I16 = auto()
    V_CMP_LT_U16 = auto(); V_CMP_EQ_U16 = auto(); V_CMP_LE_U16 = auto()
    V_CMP_GT_U16 = auto(); V_CMP_NE_U16 = auto(); V_CMP_GE_U16 = auto()
    V_CMP_F_I32 = auto(); V_CMP_LT_I32 = auto(); V_CMP_EQ_I32 = auto()
    V_CMP_LE_I32 = auto(); V_CMP_GT_I32 = auto(); V_CMP_NE_I32 = auto()
    V_CMP_GE_I32 = auto(); V_CMP_T_I32 = auto(); V_CMP_F_U32 = auto()
    V_CMP_LT_U32 = auto(); V_CMP_EQ_U32 = auto(); V_CMP_LE_U32 = auto()
    V_CMP_GT_U32 = auto(); V_CMP_NE_U32 = auto(); V_CMP_GE_U32 = auto()
    V_CMP_T_U32 = auto(); V_CMP_F_I64 = auto(); V_CMP_LT_I64 = auto()
    V_CMP_EQ_I64 = auto(); V_CMP_LE_I64 = auto(); V_CMP_GT_I64 = auto()
    V_CMP_NE_I64 = auto(); V_CMP_GE_I64 = auto(); V_CMP_T_I64 = auto()
    V_CMP_F_U64 = auto(); V_CMP_LT_U64 = auto(); V_CMP_EQ_U64 = auto()
    V_CMP_LE_U64 = auto(); V_CMP_GT_U64 = auto(); V_CMP_NE_U64 = auto()
    V_CMP_GE_U64 = auto(); V_CMP_T_U64 = auto(); V_CMP_CLASS_F16 = auto()
    V_CMP_CLASS_F32 = auto(); V_CMP_CLASS_F64 = auto(); V_CMPX_F_F16 = auto()
    V_CMPX_LT_F16 = auto(); V_CMPX_EQ_F16 = auto(); V_CMPX_LE_F16 = auto()
    V_CMPX_GT_F16 = auto(); V_CMPX_LG_F16 = auto(); V_CMPX_GE_F16 = auto()
    V_CMPX_O_F16 = auto(); V_CMPX_U_F16 = auto(); V_CMPX_NGE_F16 = auto()
    V_CMPX_NLG_F16 = auto(); V_CMPX_NGT_F16 = auto(); V_CMPX_NLE_F16 = auto()
    V_CMPX_NEQ_F16 = auto(); V_CMPX_NLT_F16 = auto(); V_CMPX_T_F16 = auto()
    V_CMPX_F_F32 = auto(); V_CMPX_LT_F32 = auto(); V_CMPX_EQ_F32 = auto()
    V_CMPX_LE_F32 = auto(); V_CMPX_GT_F32 = auto(); V_CMPX_LG_F32 = auto()
    V_CMPX_GE_F32 = auto(); V_CMPX_O_F32 = auto(); V_CMPX_U_F32 = auto()
    V_CMPX_NGE_F32 = auto(); V_CMPX_NLG_F32 = auto(); V_CMPX_NGT_F32 = auto()
    V_CMPX_NLE_F32 = auto(); V_CMPX_NEQ_F32 = auto(); V_CMPX_NLT_F32 = auto()
    V_CMPX_T_F32 = auto(); V_CMPX_F_F64 = auto(); V_CMPX_LT_F64 = auto()
    V_CMPX_EQ_F64 = auto(); V_CMPX_LE_F64 = auto(); V_CMPX_GT_F64 = auto()
    V_CMPX_LG_F64 = auto(); V_CMPX_GE_F64 = auto(); V_CMPX_O_F64 = auto()
    V_CMPX_U_F64 = auto(); V_CMPX_NGE_F64 = auto(); V_CMPX_NLG_F64 = auto()
    V_CMPX_NGT_F64 = auto(); V_CMPX_NLE_F64 = auto(); V_CMPX_NEQ_F64 = auto()
    V_CMPX_NLT_F64 = auto(); V_CMPX_T_F64 = auto(); V_CMPX_LT_I16 = auto()
    V_CMPX_EQ_I16 = auto(); V_CMPX_LE_I16 = auto(); V_CMPX_GT_I16 = auto()
    V_CMPX_NE_I16 = auto(); V_CMPX_GE_I16 = auto(); V_CMPX_LT_U16 = auto()
    V_CMPX_EQ_U16 = auto(); V_CMPX_LE_U16 = auto(); V_CMPX_GT_U16 = auto()
    V_CMPX_NE_U16 = auto(); V_CMPX_GE_U16 = auto(); V_CMPX_F_I32 = auto()
    V_CMPX_LT_I32 = auto(); V_CMPX_EQ_I32 = auto(); V_CMPX_LE_I32 = auto()
    V_CMPX_GT_I32 = auto(); V_CMPX_NE_I32 = auto(); V_CMPX_GE_I32 = auto()
    V_CMPX_T_I32 = auto(); V_CMPX_F_U32 = auto(); V_CMPX_LT_U32 = auto()
    V_CMPX_EQ_U32 = auto(); V_CMPX_LE_U32 = auto(); V_CMPX_GT_U32 = auto()
    V_CMPX_NE_U32 = auto(); V_CMPX_GE_U32 = auto(); V_CMPX_T_U32 = auto()
    V_CMPX_F_I64 = auto(); V_CMPX_LT_I64 = auto(); V_CMPX_EQ_I64 = auto()
    V_CMPX_LE_I64 = auto(); V_CMPX_GT_I64 = auto(); V_CMPX_NE_I64 = auto()
    V_CMPX_GE_I64 = auto(); V_CMPX_T_I64 = auto(); V_CMPX_F_U64 = auto()
    V_CMPX_LT_U64 = auto(); V_CMPX_EQ_U64 = auto(); V_CMPX_LE_U64 = auto()
    V_CMPX_GT_U64 = auto(); V_CMPX_NE_U64 = auto(); V_CMPX_GE_U64 = auto()
    V_CMPX_T_U64 = auto(); V_CMPX_CLASS_F16 = auto(); V_CMPX_CLASS_F32 = auto()
    V_CMPX_CLASS_F64 = auto()

    # ** VOP3 - 2/3in - 1out - 64bit encoding **
    V_FMA_DX9_ZERO_F32 = auto(); V_MAD_I32_I24 = auto(); V_MAD_U32_U24 = auto()
    V_CUBEID_F32 = auto(); V_CUBESC_F32 = auto(); V_CUBETC_F32 = auto()
    V_CUBEMA_F32 = auto(); V_BFE_U32 = auto(); V_BFE_I32 = auto()
    V_BFI_B32 = auto(); V_FMA_F32 = auto(); V_FMA_F64 = auto()
    V_LERP_U8 = auto(); V_ALIGNBIT_B32 = auto(); V_ALIGNBYTE_B32 = auto()
    V_MULLIT_F32 = auto(); V_MIN3_F32 = auto(); V_MIN3_I32 = auto()
    V_MIN3_U32 = auto(); V_MAX3_F32 = auto(); V_MAX3_I32 = auto()
    V_MAX3_U32 = auto(); V_MED3_F32 = auto(); V_MED3_I32 = auto()
    V_MED3_U32 = auto(); V_SAD_U8 = auto(); V_SAD_HI_U8 = auto()
    V_SAD_U16 = auto(); V_SAD_U32 = auto(); V_CVT_PK_U8_F32 = auto()
    V_DIV_FIXUP_F32 = auto(); V_DIV_FIXUP_F64 = auto(); V_DIV_FMAS_F32 = auto()
    V_DIV_FMAS_F64 = auto(); V_MSAD_U8 = auto(); V_QSAD_PK_U16_U8 = auto()
    V_MQSAD_PK_U16_U8 = auto(); V_MQSAD_U32_U8 = auto(); V_XOR3_B32 = auto()
    V_MAD_U16 = auto(); V_PERM_B32 = auto(); V_XAD_U32 = auto()
    V_LSHL_ADD_U32 = auto(); V_ADD_LSHL_U32 = auto(); V_FMA_F16 = auto()
    V_MIN3_F16 = auto(); V_MIN3_I16 = auto(); V_MIN3_U16 = auto()
    V_MAX3_F16 = auto(); V_MAX3_I16 = auto(); V_MAX3_U16 = auto()
    V_MED3_F16 = auto(); V_MED3_I16 = auto(); V_MED3_U16 = auto()
    V_MAD_I16 = auto(); V_DIV_FIXUP_F16 = auto(); V_ADD3_U32 = auto()
    V_LSHL_OR_B32 = auto(); V_AND_OR_B32 = auto(); V_OR3_B32 = auto()
    V_MAD_U32_U16 = auto(); V_MAD_I32_I16 = auto(); V_PERMLANE16_B32 = auto()
    V_PERMLANEX16_B32 = auto(); V_CNDMASK_B16 = auto(); V_MAXMIN_F32 = auto()
    V_MINMAX_F32 = auto(); V_MAXMIN_F16 = auto(); V_MINMAX_F16 = auto()
    V_MAXMIN_U32 = auto(); V_MINMAX_U32 = auto(); V_MAXMIN_I32 = auto()
    V_MINMAX_I32 = auto(); V_DOT2_F16_F16 = auto(); V_DOT2_BF16_BF16 = auto()
    V_ADD_NC_U16 = auto(); V_SUB_NC_U16 = auto(); V_MUL_LO_U16 = auto()
    V_CVT_PK_I16_F32 = auto(); V_CVT_PK_U16_F32 = auto(); V_MAX_U16 = auto()
    V_MAX_I16 = auto(); V_MIN_U16 = auto(); V_MIN_I16 = auto()
    V_ADD_NC_I16 = auto(); V_SUB_NC_I16 = auto(); V_PACK_B32_F16 = auto()
    V_CVT_PK_NORM_I16_F16 = auto(); V_CVT_PK_NORM_U16_F16 = auto(); V_LDEXP_F32 = auto()
    V_BFM_B32 = auto(); V_BCNT_U32_B32 = auto(); V_MBCNT_LO_U32_B32 = auto()
    V_MBCNT_HI_U32_B32 = auto(); V_CVT_PK_NORM_I16_F32 = auto(); V_CVT_PK_NORM_U16_F32 = auto()
    V_CVT_PK_U16_U32 = auto(); V_CVT_PK_I16_I32 = auto(); V_SUB_NC_I32 = auto()
    V_ADD_NC_I32 = auto(); V_ADD_F64 = auto(); V_MUL_F64 = auto()
    V_MIN_F64 = auto(); V_MAX_F64 = auto(); V_LDEXP_F64 = auto()
    V_MUL_LO_U32 = auto(); V_MUL_HI_U32 = auto(); V_MUL_HI_I32 = auto()
    V_TRIG_PREOP_F64 = auto(); V_LSHLREV_B16 = auto(); V_LSHRREV_B16 = auto()
    V_ASHRREV_I16 = auto(); V_LSHLREV_B64 = auto(); V_LSHRREV_B64 = auto()
    V_ASHRREV_I64 = auto(); V_READLANE_B32 = auto(); V_WRITELANE_B32 = auto()
    V_AND_B16 = auto(); V_OR_B16 = auto(); V_XOR_B16 = auto()

    # ** VOP3SD - 3in - VGPR and SGPR out - 64bit encoding **
    V_DIV_SCALE_F32 = auto(); V_DIV_SCALE_F64 = auto(); V_MAD_U64_U32 = auto()
    V_MAD_I64_I32 = auto(); V_ADD_CO_U32 = auto(); V_SUB_CO_U32 = auto()
    V_SUBREV_CO_U32 = auto()

    # ** VOP3P - 2/3in - 1out - packed 16bit **
    V_PK_MAD_I16 = auto(); V_PK_MUL_LO_U16 = auto(); V_PK_ADD_I16 = auto()
    V_PK_SUB_I16 = auto(); V_PK_LSHLREV_B16 = auto(); V_PK_LSHRREV_B16 = auto()
    V_PK_ASHRREV_I16 = auto(); V_PK_MAX_I16 = auto(); V_PK_MIN_I16 = auto()
    V_PK_MAD_U16 = auto(); V_PK_ADD_U16 = auto(); V_PK_SUB_U16 = auto()
    V_PK_MAX_U16 = auto(); V_PK_MIN_U16 = auto(); V_PK_FMA_F16 = auto()
    V_PK_ADD_F16 = auto(); V_PK_MUL_F16 = auto(); V_PK_MIN_F16 = auto()
    V_PK_MAX_F16 = auto(); V_DOT2_F32_F16 = auto(); V_DOT4_I32_IU8 = auto()
    V_DOT4_U32_U8 = auto(); V_DOT8_I32_IU4 = auto(); V_DOT8_U32_U4 = auto()
    V_DOT2_F32_BF16 = auto(); V_FMA_MIX_F32 = auto(); V_FMA_MIXLO_F16 = auto()
    V_FMA_MIXHI_F16 = auto(); V_WMMA_F32_16X16X16_F16 = auto(); V_WMMA_F32_16X16X16_BF16 = auto()
    V_WMMA_F16_16X16X16_F16 = auto(); V_WMMA_BF16_16X16X16_BF16 = auto(); V_WMMA_I32_16X16X16_IU8 = auto()
    V_WMMA_I32_16X16X16_IU4 = auto()

    # ** VOPD - 2 ops - 2out - dual issue **
    V_DUAL_FMAC_F32 = auto(); V_DUAL_FMAAK_F32 = auto(); V_DUAL_FMAMK_F32 = auto()
    V_DUAL_MUL_F32 = auto(); V_DUAL_ADD_F32 = auto(); V_DUAL_SUB_F32 = auto()
    V_DUAL_SUBREV_F32 = auto(); V_DUAL_MUL_DX9_ZERO_F32 = auto(); V_DUAL_MOV_B32 = auto()
    V_DUAL_CNDMASK_B32 = auto(); V_DUAL_MAX_F32 = auto(); V_DUAL_MIN_F32 = auto()
    V_DUAL_DOT2ACC_F32_F16 = auto(); V_DUAL_DOT2ACC_F32_BF16 = auto(); V_DUAL_ADD_NC_U32 = auto()
    V_DUAL_LSHLREV_B32 = auto(); V_DUAL_AND_B32 = auto()

    # ** VINTERP - interpolation in - VGPR out **
    V_INTERP_P10_F32 = auto(); V_INTERP_P2_F32 = auto(); V_INTERP_P10_F16_F32 = auto()
    V_INTERP_P2_F16_F32 = auto(); V_INTERP_P10_RTZ_F16_F32 = auto(); V_INTERP_P2_RTZ_F16_F32 = auto()

    # ** LDSDIR - parameter/LDS in - VGPR out **
    LDS_PARAM_LOAD = auto(); LDS_DIRECT_LOAD = auto()

    # ** DS - LDS/GDS memory in - VGPR out **
    DS_ADD_U32 = auto(); DS_SUB_U32 = auto(); DS_RSUB_U32 = auto()
    DS_INC_U32 = auto(); DS_DEC_U32 = auto(); DS_MIN_I32 = auto()
    DS_MAX_I32 = auto(); DS_MIN_U32 = auto(); DS_MAX_U32 = auto()
    DS_AND_B32 = auto(); DS_OR_B32 = auto(); DS_XOR_B32 = auto()
    DS_MSKOR_B32 = auto(); DS_STORE_B32 = auto(); DS_STORE_2ADDR_B32 = auto()
    DS_STORE_2ADDR_STRIDE64_B32 = auto(); DS_CMPSTORE_B32 = auto(); DS_CMPSTORE_F32 = auto()
    DS_MIN_F32 = auto(); DS_MAX_F32 = auto(); DS_NOP = auto()
    DS_ADD_F32 = auto(); DS_GWS_SEMA_RELEASE_ALL = auto(); DS_GWS_INIT = auto()
    DS_GWS_SEMA_V = auto(); DS_GWS_SEMA_BR = auto(); DS_GWS_SEMA_P = auto()
    DS_GWS_BARRIER = auto(); DS_STORE_B8 = auto(); DS_STORE_B16 = auto()
    DS_ADD_RTN_U32 = auto(); DS_SUB_RTN_U32 = auto(); DS_RSUB_RTN_U32 = auto()
    DS_INC_RTN_U32 = auto(); DS_DEC_RTN_U32 = auto(); DS_MIN_RTN_I32 = auto()
    DS_MAX_RTN_I32 = auto(); DS_MIN_RTN_U32 = auto(); DS_MAX_RTN_U32 = auto()
    DS_AND_RTN_B32 = auto(); DS_OR_RTN_B32 = auto(); DS_XOR_RTN_B32 = auto()
    DS_MSKOR_RTN_B32 = auto(); DS_STOREXCHG_RTN_B32 = auto(); DS_STOREXCHG_2ADDR_RTN_B32 = auto()
    DS_STOREXCHG_2ADDR_STRIDE64_RTN_B32 = auto(); DS_CMPSTORE_RTN_B32 = auto(); DS_CMPSTORE_RTN_F32 = auto()
    DS_MIN_RTN_F32 = auto(); DS_MAX_RTN_F32 = auto(); DS_WRAP_RTN_B32 = auto()
    DS_SWIZZLE_B32 = auto(); DS_LOAD_B32 = auto(); DS_LOAD_2ADDR_B32 = auto()
    DS_LOAD_2ADDR_STRIDE64_B32 = auto(); DS_LOAD_I8 = auto(); DS_LOAD_U8 = auto()
    DS_LOAD_I16 = auto(); DS_LOAD_U16 = auto(); DS_CONSUME = auto()
    DS_APPEND = auto(); DS_ORDERED_COUNT = auto(); DS_ADD_U64 = auto()
    DS_SUB_U64 = auto(); DS_RSUB_U64 = auto(); DS_INC_U64 = auto()
    DS_DEC_U64 = auto(); DS_MIN_I64 = auto(); DS_MAX_I64 = auto()
    DS_MIN_U64 = auto(); DS_MAX_U64 = auto(); DS_AND_B64 = auto()
    DS_OR_B64 = auto(); DS_XOR_B64 = auto(); DS_MSKOR_B64 = auto()
    DS_STORE_B64 = auto(); DS_STORE_2ADDR_B64 = auto(); DS_STORE_2ADDR_STRIDE64_B64 = auto()
    DS_CMPSTORE_B64 = auto(); DS_CMPSTORE_F64 = auto(); DS_MIN_F64 = auto()
    DS_MAX_F64 = auto(); DS_ADD_RTN_U64 = auto(); DS_SUB_RTN_U64 = auto()
    DS_RSUB_RTN_U64 = auto(); DS_INC_RTN_U64 = auto(); DS_DEC_RTN_U64 = auto()
    DS_MIN_RTN_I64 = auto(); DS_MAX_RTN_I64 = auto(); DS_MIN_RTN_U64 = auto()
    DS_MAX_RTN_U64 = auto(); DS_AND_RTN_B64 = auto(); DS_OR_RTN_B64 = auto()
    DS_XOR_RTN_B64 = auto(); DS_MSKOR_RTN_B64 = auto(); DS_STOREXCHG_RTN_B64 = auto()
    DS_STOREXCHG_2ADDR_RTN_B64 = auto(); DS_STOREXCHG_2ADDR_STRIDE64_RTN_B64 = auto(); DS_CMPSTORE_RTN_B64 = auto()
    DS_CMPSTORE_RTN_F64 = auto(); DS_MIN_RTN_F64 = auto(); DS_MAX_RTN_F64 = auto()
    DS_LOAD_B64 = auto(); DS_LOAD_2ADDR_B64 = auto(); DS_LOAD_2ADDR_STRIDE64_B64 = auto()
    DS_ADD_RTN_F32 = auto(); DS_ADD_GS_REG_RTN = auto(); DS_SUB_GS_REG_RTN = auto()
    DS_CONDXCHG32_RTN_B64 = auto(); DS_STORE_B8_D16_HI = auto(); DS_STORE_B16_D16_HI = auto()
    DS_LOAD_U8_D16 = auto(); DS_LOAD_U8_D16_HI = auto(); DS_LOAD_I8_D16 = auto()
    DS_LOAD_I8_D16_HI = auto(); DS_LOAD_U16_D16 = auto(); DS_LOAD_U16_D16_HI = auto()
    DS_BVH_STACK_RTN_B32 = auto(); DS_STORE_ADDTID_B32 = auto(); DS_LOAD_ADDTID_B32 = auto()
    DS_PERMUTE_B32 = auto(); DS_BPERMUTE_B32 = auto(); DS_STORE_B96 = auto()
    DS_STORE_B128 = auto(); DS_LOAD_B96 = auto(); DS_LOAD_B128 = auto()

    # ** MTBUF - typed buffer memory in - VGPR out **
    TBUFFER_LOAD_FORMAT_X = auto(); TBUFFER_LOAD_FORMAT_XY = auto(); TBUFFER_LOAD_FORMAT_XYZ = auto()
    TBUFFER_LOAD_FORMAT_XYZW = auto(); TBUFFER_STORE_FORMAT_X = auto(); TBUFFER_STORE_FORMAT_XY = auto()
    TBUFFER_STORE_FORMAT_XYZ = auto(); TBUFFER_STORE_FORMAT_XYZW = auto(); TBUFFER_LOAD_D16_FORMAT_X = auto()
    TBUFFER_LOAD_D16_FORMAT_XY = auto(); TBUFFER_LOAD_D16_FORMAT_XYZ = auto(); TBUFFER_LOAD_D16_FORMAT_XYZW = auto()
    TBUFFER_STORE_D16_FORMAT_X = auto(); TBUFFER_STORE_D16_FORMAT_XY = auto(); TBUFFER_STORE_D16_FORMAT_XYZ = auto()
    TBUFFER_STORE_D16_FORMAT_XYZW = auto()

    # ** MUBUF - buffer memory in - VGPR out **
    BUFFER_LOAD_FORMAT_X = auto(); BUFFER_LOAD_FORMAT_XY = auto(); BUFFER_LOAD_FORMAT_XYZ = auto()
    BUFFER_LOAD_FORMAT_XYZW = auto(); BUFFER_STORE_FORMAT_X = auto(); BUFFER_STORE_FORMAT_XY = auto()
    BUFFER_STORE_FORMAT_XYZ = auto(); BUFFER_STORE_FORMAT_XYZW = auto(); BUFFER_LOAD_D16_FORMAT_X = auto()
    BUFFER_LOAD_D16_FORMAT_XY = auto(); BUFFER_LOAD_D16_FORMAT_XYZ = auto(); BUFFER_LOAD_D16_FORMAT_XYZW = auto()
    BUFFER_STORE_D16_FORMAT_X = auto(); BUFFER_STORE_D16_FORMAT_XY = auto(); BUFFER_STORE_D16_FORMAT_XYZ = auto()
    BUFFER_STORE_D16_FORMAT_XYZW = auto(); BUFFER_LOAD_U8 = auto(); BUFFER_LOAD_I8 = auto()
    BUFFER_LOAD_U16 = auto(); BUFFER_LOAD_I16 = auto(); BUFFER_LOAD_B32 = auto()
    BUFFER_LOAD_B64 = auto(); BUFFER_LOAD_B96 = auto(); BUFFER_LOAD_B128 = auto()
    BUFFER_STORE_B8 = auto(); BUFFER_STORE_B16 = auto(); BUFFER_STORE_B32 = auto()
    BUFFER_STORE_B64 = auto(); BUFFER_STORE_B96 = auto(); BUFFER_STORE_B128 = auto()
    BUFFER_LOAD_D16_U8 = auto(); BUFFER_LOAD_D16_I8 = auto(); BUFFER_LOAD_D16_B16 = auto()
    BUFFER_LOAD_D16_HI_U8 = auto(); BUFFER_LOAD_D16_HI_I8 = auto(); BUFFER_LOAD_D16_HI_B16 = auto()
    BUFFER_STORE_D16_HI_B8 = auto(); BUFFER_STORE_D16_HI_B16 = auto(); BUFFER_LOAD_D16_HI_FORMAT_X = auto()
    BUFFER_STORE_D16_HI_FORMAT_X = auto(); BUFFER_GL0_INV = auto(); BUFFER_GL1_INV = auto()
    BUFFER_LOAD_LDS_U8 = auto(); BUFFER_LOAD_LDS_I8 = auto(); BUFFER_LOAD_LDS_U16 = auto()
    BUFFER_LOAD_LDS_I16 = auto(); BUFFER_LOAD_LDS_B32 = auto(); BUFFER_LOAD_LDS_FORMAT_X = auto()
    BUFFER_ATOMIC_SWAP_B32 = auto(); BUFFER_ATOMIC_CMPSWAP_B32 = auto(); BUFFER_ATOMIC_ADD_U32 = auto()
    BUFFER_ATOMIC_SUB_U32 = auto(); BUFFER_ATOMIC_CSUB_U32 = auto(); BUFFER_ATOMIC_MIN_I32 = auto()
    BUFFER_ATOMIC_MIN_U32 = auto(); BUFFER_ATOMIC_MAX_I32 = auto(); BUFFER_ATOMIC_MAX_U32 = auto()
    BUFFER_ATOMIC_AND_B32 = auto(); BUFFER_ATOMIC_OR_B32 = auto(); BUFFER_ATOMIC_XOR_B32 = auto()
    BUFFER_ATOMIC_INC_U32 = auto(); BUFFER_ATOMIC_DEC_U32 = auto(); BUFFER_ATOMIC_SWAP_B64 = auto()
    BUFFER_ATOMIC_CMPSWAP_B64 = auto(); BUFFER_ATOMIC_ADD_U64 = auto(); BUFFER_ATOMIC_SUB_U64 = auto()
    BUFFER_ATOMIC_MIN_I64 = auto(); BUFFER_ATOMIC_MIN_U64 = auto(); BUFFER_ATOMIC_MAX_I64 = auto()
    BUFFER_ATOMIC_MAX_U64 = auto(); BUFFER_ATOMIC_AND_B64 = auto(); BUFFER_ATOMIC_OR_B64 = auto()
    BUFFER_ATOMIC_XOR_B64 = auto(); BUFFER_ATOMIC_INC_U64 = auto(); BUFFER_ATOMIC_DEC_U64 = auto()
    BUFFER_ATOMIC_CMPSWAP_F32 = auto(); BUFFER_ATOMIC_MIN_F32 = auto(); BUFFER_ATOMIC_MAX_F32 = auto()
    BUFFER_ATOMIC_ADD_F32 = auto()

    # ** MIMG - image memory in - VGPR out **
    IMAGE_LOAD = auto(); IMAGE_LOAD_MIP = auto(); IMAGE_LOAD_PCK = auto()
    IMAGE_LOAD_PCK_SGN = auto(); IMAGE_LOAD_MIP_PCK = auto(); IMAGE_LOAD_MIP_PCK_SGN = auto()
    IMAGE_STORE = auto(); IMAGE_STORE_MIP = auto(); IMAGE_STORE_PCK = auto()
    IMAGE_STORE_MIP_PCK = auto(); IMAGE_ATOMIC_SWAP = auto(); IMAGE_ATOMIC_CMPSWAP = auto()
    IMAGE_ATOMIC_ADD = auto(); IMAGE_ATOMIC_SUB = auto(); IMAGE_ATOMIC_SMIN = auto()
    IMAGE_ATOMIC_UMIN = auto(); IMAGE_ATOMIC_SMAX = auto(); IMAGE_ATOMIC_UMAX = auto()
    IMAGE_ATOMIC_AND = auto(); IMAGE_ATOMIC_OR = auto(); IMAGE_ATOMIC_XOR = auto()
    IMAGE_ATOMIC_INC = auto(); IMAGE_ATOMIC_DEC = auto(); IMAGE_GET_RESINFO = auto()
    IMAGE_MSAA_LOAD = auto(); IMAGE_BVH_INTERSECT_RAY = auto(); IMAGE_BVH64_INTERSECT_RAY = auto()
    IMAGE_SAMPLE = auto(); IMAGE_SAMPLE_D = auto(); IMAGE_SAMPLE_L = auto()
    IMAGE_SAMPLE_B = auto(); IMAGE_SAMPLE_LZ = auto(); IMAGE_SAMPLE_C = auto()
    IMAGE_SAMPLE_C_D = auto(); IMAGE_SAMPLE_C_L = auto(); IMAGE_SAMPLE_C_B = auto()
    IMAGE_SAMPLE_C_LZ = auto(); IMAGE_SAMPLE_O = auto(); IMAGE_SAMPLE_D_O = auto()
    IMAGE_SAMPLE_L_O = auto(); IMAGE_SAMPLE_B_O = auto(); IMAGE_SAMPLE_LZ_O = auto()
    IMAGE_SAMPLE_C_O = auto(); IMAGE_SAMPLE_C_D_O = auto(); IMAGE_SAMPLE_C_L_O = auto()
    IMAGE_SAMPLE_C_B_O = auto(); IMAGE_SAMPLE_C_LZ_O = auto(); IMAGE_GATHER4 = auto()
    IMAGE_GATHER4_L = auto(); IMAGE_GATHER4_B = auto(); IMAGE_GATHER4_LZ = auto()
    IMAGE_GATHER4_C = auto(); IMAGE_GATHER4_C_LZ = auto(); IMAGE_GATHER4_O = auto()
    IMAGE_GATHER4_LZ_O = auto(); IMAGE_GATHER4_C_LZ_O = auto(); IMAGE_GET_LOD = auto()
    IMAGE_SAMPLE_D_G16 = auto(); IMAGE_SAMPLE_C_D_G16 = auto(); IMAGE_SAMPLE_D_O_G16 = auto()
    IMAGE_SAMPLE_C_D_O_G16 = auto(); IMAGE_SAMPLE_CL = auto(); IMAGE_SAMPLE_D_CL = auto()
    IMAGE_SAMPLE_B_CL = auto(); IMAGE_SAMPLE_C_CL = auto(); IMAGE_SAMPLE_C_D_CL = auto()
    IMAGE_SAMPLE_C_B_CL = auto(); IMAGE_SAMPLE_CL_O = auto(); IMAGE_SAMPLE_D_CL_O = auto()
    IMAGE_SAMPLE_B_CL_O = auto(); IMAGE_SAMPLE_C_CL_O = auto(); IMAGE_SAMPLE_C_D_CL_O = auto()
    IMAGE_SAMPLE_C_B_CL_O = auto(); IMAGE_SAMPLE_C_D_CL_G16 = auto(); IMAGE_SAMPLE_D_CL_O_G16 = auto()
    IMAGE_SAMPLE_C_D_CL_O_G16 = auto(); IMAGE_SAMPLE_D_CL_G16 = auto(); IMAGE_GATHER4_CL = auto()
    IMAGE_GATHER4_B_CL = auto(); IMAGE_GATHER4_C_CL = auto(); IMAGE_GATHER4_C_L = auto()
    IMAGE_GATHER4_C_B = auto(); IMAGE_GATHER4_C_B_CL = auto(); IMAGE_GATHER4H = auto()

    # ** FLAT - flat memory in - VGPR out **
    FLAT_LOAD_U8 = auto(); FLAT_LOAD_I8 = auto(); FLAT_LOAD_U16 = auto()
    FLAT_LOAD_I16 = auto(); FLAT_LOAD_B32 = auto(); FLAT_LOAD_B64 = auto()
    FLAT_LOAD_B96 = auto(); FLAT_LOAD_B128 = auto(); FLAT_STORE_B8 = auto()
    FLAT_STORE_B16 = auto(); FLAT_STORE_B32 = auto(); FLAT_STORE_B64 = auto()
    FLAT_STORE_B96 = auto(); FLAT_STORE_B128 = auto(); FLAT_LOAD_D16_U8 = auto()
    FLAT_LOAD_D16_I8 = auto(); FLAT_LOAD_D16_B16 = auto(); FLAT_LOAD_D16_HI_U8 = auto()
    FLAT_LOAD_D16_HI_I8 = auto(); FLAT_LOAD_D16_HI_B16 = auto(); FLAT_STORE_D16_HI_B8 = auto()
    FLAT_STORE_D16_HI_B16 = auto(); GLOBAL_LOAD_ADDTID_B32 = auto(); GLOBAL_STORE_ADDTID_B32 = auto()
    GLOBAL_LOAD_LDS_ADDTID_B32 = auto(); FLAT_ATOMIC_SWAP_B32 = auto(); FLAT_ATOMIC_CMPSWAP_B32 = auto()
    FLAT_ATOMIC_ADD_U32 = auto(); FLAT_ATOMIC_SUB_U32 = auto(); FLAT_ATOMIC_CSUB_U32 = auto()
    FLAT_ATOMIC_MIN_I32 = auto(); FLAT_ATOMIC_MIN_U32 = auto(); FLAT_ATOMIC_MAX_I32 = auto()
    FLAT_ATOMIC_MAX_U32 = auto(); FLAT_ATOMIC_AND_B32 = auto(); FLAT_ATOMIC_OR_B32 = auto()
    FLAT_ATOMIC_XOR_B32 = auto(); FLAT_ATOMIC_INC_U32 = auto(); FLAT_ATOMIC_DEC_U32 = auto()
    FLAT_ATOMIC_SWAP_B64 = auto(); FLAT_ATOMIC_CMPSWAP_B64 = auto(); FLAT_ATOMIC_ADD_U64 = auto()
    FLAT_ATOMIC_SUB_U64 = auto(); FLAT_ATOMIC_MIN_I64 = auto(); FLAT_ATOMIC_MIN_U64 = auto()
    FLAT_ATOMIC_MAX_I64 = auto(); FLAT_ATOMIC_MAX_U64 = auto(); FLAT_ATOMIC_AND_B64 = auto()
    FLAT_ATOMIC_OR_B64 = auto(); FLAT_ATOMIC_XOR_B64 = auto(); FLAT_ATOMIC_INC_U64 = auto()
    FLAT_ATOMIC_DEC_U64 = auto(); FLAT_ATOMIC_CMPSWAP_F32 = auto(); FLAT_ATOMIC_MIN_F32 = auto()
    FLAT_ATOMIC_MAX_F32 = auto(); FLAT_ATOMIC_ADD_F32 = auto()

    # ** GLOBAL - global memory in - VGPR out **
    GLOBAL_LOAD_U8 = auto(); GLOBAL_LOAD_I8 = auto(); GLOBAL_LOAD_U16 = auto()
    GLOBAL_LOAD_I16 = auto(); GLOBAL_LOAD_B32 = auto(); GLOBAL_LOAD_B64 = auto()
    GLOBAL_LOAD_B96 = auto(); GLOBAL_LOAD_B128 = auto(); GLOBAL_STORE_B8 = auto()
    GLOBAL_STORE_B16 = auto(); GLOBAL_STORE_B32 = auto(); GLOBAL_STORE_B64 = auto()
    GLOBAL_STORE_B96 = auto(); GLOBAL_STORE_B128 = auto(); GLOBAL_LOAD_D16_U8 = auto()
    GLOBAL_LOAD_D16_I8 = auto(); GLOBAL_LOAD_D16_B16 = auto(); GLOBAL_LOAD_D16_HI_U8 = auto()
    GLOBAL_LOAD_D16_HI_I8 = auto(); GLOBAL_LOAD_D16_HI_B16 = auto(); GLOBAL_STORE_D16_HI_B8 = auto()
    GLOBAL_STORE_D16_HI_B16 = auto(); GLOBAL_LOAD_LDS_U8 = auto(); GLOBAL_LOAD_LDS_I8 = auto()
    GLOBAL_LOAD_LDS_U16 = auto(); GLOBAL_LOAD_LDS_I16 = auto(); GLOBAL_LOAD_LDS_B32 = auto()
    GLOBAL_ATOMIC_SWAP_B32 = auto(); GLOBAL_ATOMIC_CMPSWAP_B32 = auto(); GLOBAL_ATOMIC_ADD_U32 = auto()
    GLOBAL_ATOMIC_SUB_U32 = auto(); GLOBAL_ATOMIC_CSUB_U32 = auto(); GLOBAL_ATOMIC_MIN_I32 = auto()
    GLOBAL_ATOMIC_MIN_U32 = auto(); GLOBAL_ATOMIC_MAX_I32 = auto(); GLOBAL_ATOMIC_MAX_U32 = auto()
    GLOBAL_ATOMIC_AND_B32 = auto(); GLOBAL_ATOMIC_OR_B32 = auto(); GLOBAL_ATOMIC_XOR_B32 = auto()
    GLOBAL_ATOMIC_INC_U32 = auto(); GLOBAL_ATOMIC_DEC_U32 = auto(); GLOBAL_ATOMIC_SWAP_B64 = auto()
    GLOBAL_ATOMIC_CMPSWAP_B64 = auto(); GLOBAL_ATOMIC_ADD_U64 = auto(); GLOBAL_ATOMIC_SUB_U64 = auto()
    GLOBAL_ATOMIC_MIN_I64 = auto(); GLOBAL_ATOMIC_MIN_U64 = auto(); GLOBAL_ATOMIC_MAX_I64 = auto()
    GLOBAL_ATOMIC_MAX_U64 = auto(); GLOBAL_ATOMIC_AND_B64 = auto(); GLOBAL_ATOMIC_OR_B64 = auto()
    GLOBAL_ATOMIC_XOR_B64 = auto(); GLOBAL_ATOMIC_INC_U64 = auto(); GLOBAL_ATOMIC_DEC_U64 = auto()
    GLOBAL_ATOMIC_CMPSWAP_F32 = auto(); GLOBAL_ATOMIC_MIN_F32 = auto(); GLOBAL_ATOMIC_MAX_F32 = auto()
    GLOBAL_ATOMIC_ADD_F32 = auto()

    # ** SCRATCH - scratch memory in - VGPR out **
    SCRATCH_LOAD_U8 = auto(); SCRATCH_LOAD_I8 = auto(); SCRATCH_LOAD_U16 = auto()
    SCRATCH_LOAD_I16 = auto(); SCRATCH_LOAD_B32 = auto(); SCRATCH_LOAD_B64 = auto()
    SCRATCH_LOAD_B96 = auto(); SCRATCH_LOAD_B128 = auto(); SCRATCH_STORE_B8 = auto()
    SCRATCH_STORE_B16 = auto(); SCRATCH_STORE_B32 = auto(); SCRATCH_STORE_B64 = auto()
    SCRATCH_STORE_B96 = auto(); SCRATCH_STORE_B128 = auto(); SCRATCH_LOAD_D16_U8 = auto()
    SCRATCH_LOAD_D16_I8 = auto(); SCRATCH_LOAD_D16_B16 = auto(); SCRATCH_LOAD_D16_HI_U8 = auto()
    SCRATCH_LOAD_D16_HI_I8 = auto(); SCRATCH_LOAD_D16_HI_B16 = auto(); SCRATCH_STORE_D16_HI_B8 = auto()
    SCRATCH_STORE_D16_HI_B16 = auto(); SCRATCH_LOAD_LDS_U8 = auto(); SCRATCH_LOAD_LDS_I8 = auto()
    SCRATCH_LOAD_LDS_U16 = auto(); SCRATCH_LOAD_LDS_I16 = auto(); SCRATCH_LOAD_LDS_B32 = auto()

    # ** EXP - 4in - export out **
    EXP = auto()
